### ISSUE TITLE
tsuquyomi for neovim

### ISSUE THREAD

**Issue by donnut** [Quramy/tsuquyomi#10]
Is there any experience running tsuquyomi with neovim?

**Comment by Quramy** [comment]
I have not tried tsuquyomi with neovim.
if you use neovim and find some issues, please report me.

**Comment by icholy** [comment]
Works fine for me.

**Comment by donnut** [comment]
Thanks @icholy, did you use vimproc on neovim for that too, or has neovim another kind of support for interactive command execution?

**Comment by donnut** [comment]
I tried it again and both vimproc and tsuquyomi work fine in neovim! Great.
