### ISSUE TITLE
Unused import detection

### ISSUE THREAD

**Issue by LeResKP** [Quramy/tsuquyomi#105]
Hello,

I didn't see anything in the doc, but I would like to let the plugin detect unused import. Even if possible a command to remove them.

Is it something supported ?

Thks,
Aurélien

**Comment by Quramy** [comment]
Hi @LeResKP .

No, my plugin does not have the feature to remove unused import / variables.

I use tslint ( https://palantir.github.io/tslint/rules/no-unused-variable/) and [syntastic](https://github.com/vim-syntastic/syntastic) to check them and remove them manually .

**Comment by LeResKP** [comment]
Hello @Quramy 

Thks for your answer, I set the no-unused variable in my tslint config, and it's okay.

Thks for the tips.
