### ISSUE TITLE
TsuImport importing from full path instead of module name

### ISSUE THREAD

**Issue by endel** [Quramy/tsuquyomi#117]
Hi there,

First of all, thanks for your effort on this plugin, it really works great!

One thing I'd like to report is that `TsuImport` sometimes gets the **full path** to the file which exports the requested definition. For some packages it doesn't happen, though. I couldn't understand why.

**Example:**

```
import { Delayed } from "clock-timer.js/dist/index";
```

The expected result on this case would be:

```
import { Delayed } from "clock-timer.js";
```

Cheers!

**Comment by Quramy** [comment]
I've wrote this limitation at README.
