### ISSUE TITLE
Your TypeScript Version is Invalid -- Tsserver path not escaping property

### ISSUE THREAD

**Issue by davidwesst** [Quramy/tsuquyomi#123]
Hello,

I've installed everything as instructed, but I'm getting a strange issue when I load up a typescript file (see image below) in Vim 8.0.445

When I run `:echo tsuquyomi#config#tsscmd()` I get full Windows path to my local node_module folder where the server lives, which is expected. The problem lies in the slashes, based on what I'm seeing in vim

![image](https://cloud.githubusercontent.com/assets/867084/24231593/910661fc-0f53-11e7-8f1d-ec2f2b33f883.png)

Any ideas on what I could do to fix this? Any direction would be helpful

**Comment by hell0world** [comment]
1. `npm install -g typescript`
2. `tsc --version` make sure the return version >=1.5.3
4. then add the following to your ~/.vimrc
> g:tsuquyomi_use_dev_node_module

read more configuration on [plugin configm.vim](https://github.com/Quramy/tsuquyomi/blob/master/autoload/tsuquyomi/config.vim)

**Comment by davidwesst** [comment]
Awesome!

The first solution worked like a charm. Would have liked to use the local typescript rather than having it installed globally, but it works! Thanks!
