### ISSUE TITLE
TsuImport should use single quotes according to tslint.

### ISSUE THREAD

**Issue by forgemo** [Quramy/tsuquyomi#124]
According to tslint (default config) , one should use single quotes instead of double quotes on imports.

To make the linter happy, I have to manually change to single quotes after every use of TsuImport.

Is it possible to make the quote type configurable?

**Comment by Quramy** [comment]
You can customize import statements' quotation via:

:let g:tsuquyomi_single_quote_import=1

**Comment by forgemo** [comment]
Works! You are my personal hero! :) Thanks for the great plugin!
