### ISSUE TITLE
Option to use vimproc in vim8

### ISSUE THREAD

**Issue by mrpeabody** [Quramy/tsuquyomi#138]
It takes a very long time to open a .ts file in vim8 when it's using native vim8 jobs. Neovim jobs aren't supported and it starts much faster when it uses vimproc plugin. (Same with vim 7.4). It would be great 
if there was an option that forces tsuquyomi to use vimproc jobs instead of default ones.

Pull request: https://github.com/Quramy/tsuquyomi/pull/139

**Comment by Quramy** [comment]
I've merged #139.
