### ISSUE TITLE
TsuquyomiGoBack not working

### ISSUE THREAD

**Issue by jomifo** [Quramy/tsuquyomi#14]
TsuquyomiDefinition works successfully, but subsequent TsuquyomiGoBack does not and messages "[Tsuquyomi] No items in navigation stack... "

**Comment by Quramy** [comment]
Was your vim window split when the definition navigation?
 
Now, TsuquyomiGoBack command can't navigate back across windows. In other words, this command is available only if the identifier are defined in the same file.

I think it is not good, and I'll improve these navigation commands.

**Comment by jomifo** [comment]
Just tried latest commit and it works as expected-  Jumps back to the original file.  Thanks.
