### ISSUE TITLE
Tsuquyomi doesn't like project paths with spaces.

### ISSUE THREAD

**Issue by 2009** [Quramy/tsuquyomi#147]
I have my project in a folder like `ionic 2/newproject` which gives me the following error:
```
Tsuquyomi] Your TypeScript version is invalid. module.js:472^@    throw err;^@    ^^@^@Error: Cannot find module '/home/user/mnt/data/dev/ionic'^@    at Function
.Module._resolveFilename (module.js:470:15)^@    at Function.Module._load (module.js:418:25)^@    at Module.runMain (module.js:605:10)^@    at run (bootstrap_node.j
s:427:7)^@    at startup (bootstrap_node.js:151:9)^@    at bootstrap_node.js:542:3
```
If I rename the `ionic 2` folder to `ionic2` it works fine.

**Comment by dubcdr** [comment]
it's pretty crazy that you use vim, yet have spaces in your directory paths.

**Comment by axvr** [comment]
@2009, I have the exact same issue, I may attempt to create and submit a patch this week if I get the chance

**Comment by 2009** [comment]
Thanks @axvr.
