### ISSUE TITLE
can't see quick fix options

### ISSUE THREAD

**Issue by fringd** [Quramy/tsuquyomi#149]
when there are 2 or more quick fixes available, the prompt asks me to select one but i can't see the options? I tried typing "1" or "2" but that didn't work.

**Comment by Quramy** [comment]
Sorry, there is a bug when an error has 2 or more quick fix candidates. I'll fix it..

**Comment by Quramy** [comment]
@fringd .

when there are 2 or more codefixes, you can select the codefix to apply using TAB key.

**Comment by fringd** [comment]
ah okay, tab works thank you ^_^
