### ISSUE TITLE
Support "tooltip" in terminal vim.

### ISSUE THREAD

**Issue by jomifo** [Quramy/tsuquyomi#15]
It would be very nice if the "tooltip" functional worked in terminal vim (which doesn't support balloon functionality).

Would it be possible to have the option to show the "tooltip" in something like the preview window?

**Comment by Quramy** [comment]
Hi, jomifo.

Considering your opinions, I add a function for "tooltip", which is `tsuquyomi#hint()`.

For example of `.vimrc`:

```vim
autocmd FileType typescript nmap <buffer> <Space>t : <C-u>echo tsuquyomi#hint()<CR>
```

The above example does not use preview window, but it works on terminal Vim.

**Comment by jomifo** [comment]
Hi Quramy-
Much thanks.  It works very good.  I like your echo mapping better than my preview window suggestion.
