### ISSUE TITLE
Duplicate "<Plug>(TsuquyomiDefinition)" in doc/tsuquyomi.jax file

### ISSUE THREAD

**Issue by alkama** [Quramy/tsuquyomi#156]
Hello,

Just a note about an error in the `/doc/tsuquyomi.jax` file.
The command `:helptags` complains about the fact `<Plug>(TsuquyomiDefinition)` exists twice.

https://github.com/Quramy/tsuquyomi/blob/254f890f2f216a5179d8612f8a2b6fa15ca461ab/doc/tsuquyomi.jax#L351

I cant read japanese, but I guess your last commit added it instead of replacing the previous one :)

Kind regards.

**Comment by Quramy** [comment]
Sorry, I'll fix it!
