### ISSUE TITLE
[Feature request] - Get typo info for variable under cursor

### ISSUE THREAD

**Issue by iscekic** [Quramy/tsuquyomi#161]
Hello,

Love your plugin! :+1:

Is there a way to get type info for a variable under the cursor?

```typescript
// cursor on x
const x = 3;
// :TsuTypeInfo<CR> -> number
```

**Comment by nickspoons** [comment]
You can use the `hint` function, I have this mapping:

    nnoremap <leader>tsh :echo tsuquyomi#hint()<cr>

**Comment by iscekic** [comment]
@nickspoons That's what I was looking for, thanks a lot. :smile:
