### ISSUE TITLE
Tsuquyomi with Syntastic doesn't report errors when opening file

### ISSUE THREAD

**Issue by moeabdol** [Quramy/tsuquyomi#162]
When I first open a file in a buffer. Tsuquyomi doesn't report any errors until I save the file with :w then the error is highlighted. Is there a configuration setting to load it at file open.

**Comment by nickspoons** [comment]
This is a Syntastic issue, not tsuquyomi. Try setting:

    let g:syntastic_check_on_open = 1

And have a look at `:help syntastic`

**Comment by moeabdol** [comment]
I already have it set in my .vimrc @nickspoons 
I'm not sure if it's a Syntastic issue. I have other checkers for ruby and they are working fine.

**Comment by nickspoons** [comment]
It's this when you open your first ts file in the session, or also subsequent files? For the first file the typescript project will need to be loaded before Syntastic can report on it.

**Comment by moeabdol** [comment]
@nickspoons this happens with every subsequent .ts file I open. I tried waiting for 2 minutes before opening my second .ts file and errors were not reported neither on the first nor second files.

Are you facing the same issue?

**Comment by nickspoons** [comment]
No I don't like to check check on file open, and I'm not at my computer to check just now sorry. You can always call `:SyntasticCheck`, and if that works fine, try adding an autocmd to call it on file open?

**Comment by moeabdol** [comment]
Calling :SyntasticCheck works fine, and I tried your suggestion.
`autocmd BufNewFile,BufRead,BufEnter,FocusGained,BufWritePre * :SyntasticCheck`
But it doesn't work. .ts files take about 5 seconds to open after I added Tsuquyomi plugin. I'm guessing that Syntastic loads before Tsuquyomi, and when it does maybe there isn't any checker active.

**Comment by moeabdol** [comment]
I'm noticing the same behavior with other Syntastic checkers; thus, I'm closing this issue as it might not be directly related to Tsuquyomi.
