### ISSUE TITLE
Can we configure tsuquyomi to also work with non .ts files like .vue

### ISSUE THREAD

**Issue by FernandoBasso** [Quramy/tsuquyomi#168]
I am working with VueJs + Typescript. The TS compiler throws errors and warnings that are not reflected on my `.vue` single file components (everything works fine on `.ts` files, though).

Is it possible to make this _tsuquyomi_ work with other filetypes? My typescript code in `.vue` files is inside script tags with `lang="ts"`.

``` html
<script lang="ts">
    // TypeScript code here...
</script>
```

**Comment by Quramy** [comment]
You might like https://github.com/Quramy/tsuquyomi-vue .

**Comment by FernandoBasso** [comment]
Wow, amazing. You are truly the chosen one! Thanks.
