### ISSUE TITLE
Cleanup compiled files

### ISSUE THREAD

**Issue by ksikka** [Quramy/tsuquyomi#17]
When I save a `foo.ts` file I notice it leaves behind the compiled `foo.js` file on the hard drive.
I tried setting `noEmit: true` and `out: /dev/null` in the `tsconfig.json` but this behavior still happens.
Any idea why this is happening and how I can stop it?

**Comment by Quramy** [comment]
Hmm,,, tsuquyomi and TSServer don't write any `*.js` files.

Do you use other relevant Vim plugins ?
(For example, [syntastic](https://github.com/scrooloose/syntastic) runs TypeScript compiler when the buffer is saved)

Or, are something other processes(such as `tsc --watch` or `gulp` or ...) watching `foo.ts` ?

**Comment by ksikka** [comment]
I am using syntastic, it's possible that it's saving the js file and it wasn't happening before since I only recently installed TSServer. Will try disabling it. thanks.

**Comment by ksikka** [comment]
Confirmed it was syntastic.
