### ISSUE TITLE
Plugin incorrectly assumes root directory

### ISSUE THREAD

**Issue by ondrowan** [Quramy/tsuquyomi#173]
My directory structure is as follows:

```
.git
src/
    package1/
        tsconfig.json
        node_modules/
        src/
            my-file.ts
    package2/
        ...
```

When I open `my-file.ts`, this plugin tries to use global Typescript because it thinks root of my project is where `.git` folder resides (judging by `Prelude.path2project_directory`), but there isn't `node_modules` with Typescript binaries in there.

**Comment by kevcenteno** [comment]
FWIW, I fixed this by using `g:tsuquyomi_use_dev_node_module = 1` and installing typescript in the tsuquyomi plugin folder.  See here for instructions  https://github.com/Quramy/tsuquyomi/blob/master/doc/tsuquyomi.txt#L258

**Comment by willfrew** [comment]
@kevcenteno that's not really a valid fix when working with multiple typescript projects that use different compiler versions.

I'm running into this while editing a [lerna](https://lernajs.io/) repo.

**Comment by willfrew** [comment]
FWIW I'm not seeing this bug anymore after `git pull`ing latest changes for the fix to https://github.com/Quramy/tsuquyomi/issues/184
