### ISSUE TITLE
Omni-completion freezes Vim, eating up 90 % of CPU time

### ISSUE THREAD

**Issue by dkvasnicka** [Quramy/tsuquyomi#174]
MacVim 8.0.891.

I open an empty TS file, type `JSON.`, hit `<C-x><C-o>` and vim freezes, eating up the CPU and spinning cooling fans. It happened with a non-empty file too (https://github.com/graphcool/serverless-plugin-typescript/blob/master/example/handler.ts) and also sometimes it just works and offers a completion menu. But most of the time it freezes.

My `tsconfig.json` (but I experienced it with none, too):

```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "target": "es2015",
    "module": "commonjs"
  }
}
```

I changed no configuration except for switching Syntastic to this plugin. Oh and sometimes it also freezes on save.

**Comment by dkvasnicka** [comment]
Looks like another instance of #82 ?

**Comment by Quramy** [comment]
Hi @dkvasnicka . `let g:tsuquyomi_use_vimproc=1` may solve it. (It requires https://github.com/Shougo/vimproc.vim )

I've tried mvim and tsuquyomi and found typescript language server sometimes throw an error.

**Comment by dkvasnicka** [comment]
Looks like this does the trick, thanks.

**Comment by krischik** [comment]
Sadly `g:tsuquyomi_use_vimproc` did not work for me. I wonder why this ticket is closed. The problem persist after all.

**Comment by AmebaBrain** [comment]
@krischik 
Same for me. `g:tsuquyomi_use_vimproc` didn't help. Regarding this closed ticket - there are another three open exist

https://github.com/Quramy/tsuquyomi/issues/140
https://github.com/Quramy/tsuquyomi/issues/121
https://github.com/Quramy/tsuquyomi/issues/57

Unfortunately on today **tsuquyomi** didn't have async implementation onboarded. After one day of frustating and digging (it stopped to work to me today but was working perfectly fine yesterday!) I had to switch to [tscompletejob](https://github.com/runoshun/tscompletejob) plugin

**Comment by towc** [comment]
This seems to happen for typescript ^1.8
I managed to at least not make it freeze by downgrading: `npm i -g typescript@1.7`, but it's hacky and I'd still like a fix :/
