### ISSUE TITLE
Quickfix split should occupy full width?

### ISSUE THREAD

**Issue by jomifo** [Quramy/tsuquyomi#18]
Is it possible to have the Quickfix window always open full width when there are vertical splits?

**Comment by Quramy** [comment]
Tsuquyomi uses `:copen` command to quickFix window.
And I confirm Vim doc with `:h cope`, but there is nothing to help how to open full-width quick fix window.

**Comment by jomifo** [comment]
Maybe this is relevant-
https://github.com/tpope/vim-dispatch/issues/4

**Comment by Quramy** [comment]
I'm going to try it...

**Comment by Quramy** [comment]
Hi, jomifo.

As your link says, it is possible.
Append the following to your '.vimrc':

```vim
autocmd filetype qf wincmd J
```

**Comment by jomifo** [comment]
I'll give that a try.  Thanks.
