### ISSUE TITLE
Error in Rename Symbol

### ISSUE THREAD

**Issue by derekpitt** [Quramy/tsuquyomi#19]
Hello!

I get this error when running `:TsuquyomiRenameSymbol`

```
[Tsuquyomi] New symbol name : AppState2Error detected while processing function tsuquyomi#renameSymbol..<SNR>89_renameSymbolWithOptions..<SNR>89_renameLocal:
line    3:
E716: Key not present in Dictionary: /Users/derek/SlideroomGIT/goodprospect2015-ui/src/models/app-state.ts
E15: Invalid expression: s:locs_dict[expand('%:p')]
line    5:
E121: Undefined variable: locations_in_buf
E15: Invalid expression: locations_in_buf

Changed 4 locations.
```

it is an export class name that I am trying to rename. Let me know if you need other information!

**Comment by Quramy** [comment]
Hi, derekpitt.

I tried to get your error, using the following sample codes. But I could not get the error.
If you don't mind,  tell me the files where the error occurred (Github repository or Gist).  

* Hoge.ts 

```typescript
module Main {
    export class Hoge {}
}
```

* Foo.ts

```typescript
/// <reference path="./Hoge.ts" />

var a = new Main.Hoge();
```

I executed `:TsuquyomiRenameSymbol` on `Hoge` at Hoge.ts, but the symbol renamed successfully.

**Comment by derekpitt** [comment]
I'm working on getting you an example repository (the error i'm getting is in a private repo)..
I'll let you know when I have something up.

**Comment by derekpitt** [comment]
alright i think i have some examples for you.

https://github.com/derekpitt/tsuquyomi-examples

To reproduce the particular issue, if you start in ex2/ and open up file2.ts and try to rename AppState in the import statement.


I also get unexpected results when going into ex1/ open up app-state.ts and try to rename the class:

it turns into:

    export class newname}

Sorry this took a long time to put together..  you know... work and stuff :)

I'm also going to see if i get similar results when using latest master branch from TypeScript (i know they have made some progress). i'll let you know what I find out!

**Comment by Quramy** [comment]
Hi, @derekpitt .

Thanks for your example repository !

I tried your issues and I reproduced them.

I'll try to fix them.

**Comment by derekpitt** [comment]
Thanks!

**Comment by Quramy** [comment]
I think that I fixed this issues(renaming `ex2/file2.ts` and `ex1/app-state.ts`).

Please confirm with checking out my latest commit ( f5898b50bf05b046bb446e55d234c5d273306bca ).

**Comment by derekpitt** [comment]
Yeah! looking real good! seems to be working much better. Thank you!!!

Is there a way to not open up each file it hits when renaming?

**Comment by Quramy** [comment]
Sorry, now I don't have the way to not open files which contains renamed symbol.
To replace symbol, I use `:split` command at [autoload/tsuquyomi.vim](autoload/tsuquyomi.vim#L631).

If you have any idea, please tell me.

**Comment by derekpitt** [comment]
maybe `:edit` could be used? or make it an option the user can set like `g:tsuquyomi_rename_split`

it may be nice to set it to `:edit` as default, since it is pretty crazy to have 50 splits if you rename something that is used a lot throughout your code :)

**Comment by Quramy** [comment]
Because I think users may dislike that the plugin arbitrarily changes and saves them source codes, `:TsuquyomiRenameSymbol` command replaces hit symbol but does not save the opened buffers. So using `:edit` instead of `:split` can occurs the following error.

 ```
Error occurred while executing "open" action
```

I'll consider your request and adding option to replace & save arbitrarily.

**Comment by derekpitt** [comment]
sounds good! thanks for getting this fixed so fast!
