### ISSUE TITLE
neovim: vital: ProcessManager: doesn't know about tsuquyomiTSServer

### ISSUE THREAD

**Issue by nicknisi** [Quramy/tsuquyomi#203]
I'm seeing the following error when opening TypeScript files in neovim.

```
Error detected while processing function 21[30]..<SNR>63_callback:
line   33:
vital: ProcessManager: doesn't know about tsuquyomiTSServer
```

This is in neovim 0.2.2, but I am not getting the error on vim 8.0.1400, both running on macOS 10.13.2.

**Comment by nicknisi** [comment]
My bad... This is because vimproc wasn't installed. All good now, thanks!

**Comment by iamwilhelm** [comment]
How were you able to figure this out? Had you not said this here, I would have been stuck.

**Comment by kurko** [comment]
I ask the same. I don't see vimproc mentioned in the error message
