### ISSUE TITLE
Support for definitions by referance

### ISSUE THREAD

**Issue by mhartington** [Quramy/tsuquyomi#22]
Not sure if this is supported at the moment but I tried to reference a type definition file and omnicomplete wouldn't work.

But if I setup the interfaces inside the file, omnicomplete works fine. 

Is this not supported?
What more informations do you need from me?

**Comment by Quramy** [comment]
Tsuquyomi supports omni-completion with separated files.

Did you write `/// <reference path="..." />` ?

**Comment by mhartington** [comment]
Yep, got my reference paths linked correctly. 
Again, if I inline my interfaces, they work fine.

**Comment by Quramy** [comment]
Ummm. I have no idea to fix your issue.

If you don't mind , please give me these files ? (gist or your repository)

**Comment by mhartington** [comment]
Was an issue with another plugin in my vimrc. 
Sorry for the issue and thanks for the awesome plugin!
