### ISSUE TITLE
Error when running tsuquyomi as a Syntastic checker

### ISSUE THREAD

**Issue by mboughaba** [Quramy/tsuquyomi#230]
Hi,

I started getting the error below after upgrading to `typescript@2.8.3` and `typescript@2.7.2`.

![image](https://user-images.githubusercontent.com/3800584/40467520-89d2940a-5f2a-11e8-89a8-118af2220fd5.png)

I couldn't find anything related to this in the documentation.

Anyone has an idea how to fix this error? Is there a way to let the plugin use a custom version of typescript?

Cheers,

**Comment by PetarMetodiev** [comment]
I get the exact same error

**Comment by mjolk** [comment]
i'm running ts 2.9.2, same error

**Comment by EvanCarroll** [comment]
@mboughaba In the future, please never use screen shoots for text.

------

In my `.vimrc`, I have

```
call plug#begin('~/.vim/plugged')                   
                                                    
Plug 'scrooloose/syntastic'                         
Plug 'Quramy/tsuquyomi'                             
                                                    
call plug#end()                                     
                                                    
                                                    
let g:syntastic_always_populate_loc_list = 1        
let g:syntastic_auto_loc_list = 1                   
let g:syntastic_check_on_open = 1                   
let g:syntastic_check_on_wq = 0                     
                                                    
let g:tsuquyomi_disable_quickfix = 1                
let g:syntastic_typescript_checkers = ['tsuquyomi'] 
```

I have a file called `tsconfig.json` it has

```
{ 
  "compilerOptions": {
    "noUnusedLocals": true
  }
}
```

My file `index.ts` which pulls in the module `rxjs` which I've installed with node-modules

    import {Observable} from 'rxjs';

When I try to open it, I get

```
"index.ts" 1L, 33C
Error detected while processing function <SNR>23_VimEnterHook[7]..<SNR>23_UpdateErrors[15]..<SNR>23_CacheErrors[39]..16[1]..15[24]..SyntaxCheckers_typescript_tsuquyomi_
GetLocList[1]..tsuquyomi#createFixlist[13]..tsuquyomi#createQuickFixListFromEvents:
line   23:
E714: List required
Press ENTER or type command to continue
Error detected while processing function <SNR>23_VimEnterHook[7]..<SNR>23_UpdateErrors[15]..<SNR>23_CacheErrors[39]..16[1]..38:
line    3:
E712: Argument of filter() must be a List or Dictionary
```

I'm not sure why I get this when I open the file, when I run `:SyntasticCheck` I get the much more reasonable,

```
index.ts|1 col 1 error| 6133[QF available]: 'Observable' is declared but its value is never read.                                                                       
```

**Comment by mjolk** [comment]
i'm consistently getting this error if i save a file with an error; just put some nonsense in a ts file and hit :w 
it's not a big deal since it only happens when you're being too fast ;)

**Comment by Quramy** [comment]
Hi guys. Sorry for my late reply. 

I handled this error via 50efc634321e97f15bf9518f0590aa210221ebfc .

**Comment by PetarMetodiev** [comment]
Still getting the error, global typescript 3.0.1

**Comment by cmain** [comment]
The root cause of this, at least in my case, appears to be:
https://github.com/Microsoft/TypeScript/issues/21804

The getCodeFixes operation then fails and `tsuquyomi` falls back to an empty body `{}` instead of a list and thats why it hits `List required`.  I took a shot at a fix here: https://github.com/Quramy/tsuquyomi/pull/243
