### ISSUE TITLE
Neovim very slow

### ISSUE THREAD

**Issue by eskinderg** [Quramy/tsuquyomi#256]
I am using 
nvim NVIM v0.3.0
Typescript v3.1.1
node v10.0.0

I have installed all the necessary plugins to make typescript autocomplete work and it is working perfectly.

My issue is that it is super slow opening typescript files and many times my machine gets stuck unless I remove "Shougo/vimproc.vim" which make navigation to definition possible and without the "Shougo/vimproc.vim", jumping to definition is not working.

I am not sure if i have to use deoplete.

**Comment by mboughaba** [comment]
I don't know about NVIM but If you have VIM 8 you don't need `Shougo/vimproc.vim` (basically job support)
> ## How to install
> Tsuquyomi requires the following:

> Vim (vim7.4 or later)
> Node.js & TypeScript
> Shougo/vimproc.vim (Not required if you use vim8 or later) <---------

I tried myself to remove it but it didn't help the performance.

**Comment by s0ber** [comment]
@eskinderg I had the same issue. Please check if setting `let g:tsuquyomi_use_vimproc = 1` helps.

I had `let g:tsuquyomi_use_vimproc = 0` for a very long time and it seems this is where the issues are coming from.
