### ISSUE TITLE
TsuRenameSymbol breaks when symbol occures twice on same line

### ISSUE THREAD

**Issue by nextchessmove** [Quramy/tsuquyomi#259]
Given this example source:

    interface LongIdentifier { }
  
    function foo(n: LongIdentifier) : LongIdentifier {
      return n;
    }

Placing the caret over the first `LongIdentifier` and running `:TsuRenameSymbol` to rename `LongIdentifier` to `Foo` results in this:

    interface Foo { }

    function foo(n: Foo) : LongIdentifFoo
      return n;
    }

I haven't dug in much to the implementation, but from the looks of it, could applying the changes "rightmost first" fix this?

Thank you for such a great plugin!

**Comment by nextchessmove** [comment]
Given this example source:

    interface LongIdentifier { }
  
    function foo(n: LongIdentifier) : LongIdentifier {
      return n;
    }

Placing the caret over the first `LongIdentifier` and running `:TsuRenameSymbol` to rename `LongIdentifier` to `Foo` results in this:

    interface Foo { }

    function foo(n: Foo) : LongIdentifFoo
      return n;
    }

I haven't dug in much to the implementation, but from the looks of it, could applying the changes "rightmost first" fix this?

Thank you for such a great plugin!

**Comment by Quramy** [comment]
I've fixed via #290
