### ISSUE TITLE
when use :TsuquyomiDefinition, how to open new tab.

### ISSUE THREAD

**Issue by pospome** [Quramy/tsuquyomi#27]
when use :TsuquyomiDefinition, how to open new tab?

i read your doc, but i can't find that setting.
https://github.com/Quramy/tsuquyomi/blob/master/doc/tsuquyomi.txt

if possible, please tell me that.

**Comment by Quramy** [comment]
Hi @pospome pospome.

Now, `:TsuquyomiDefinition` has three options: (see `help tsuquyomi-variables`).

```
						*g:tsuquyomi_definition_split*
g:tsuquyomi_definition_split	(default 0)
		Whether to open a new split when navigating to definition in
		another file when calling |:TsuquyomiDefinition|.
		* 0: |:edit|
		* 1: |:split|
		* 2: |:vplit|

					*g:tsuquyomi_completion_case_sensitive*
```

But there is no option to open in a new tab.

**Comment by pospome** [comment]
i see options.
i use vim command "tab ba".
thanks.

**Comment by pospome** [comment]
i confirmed to open new tab.
thanks for speedy response.

**Comment by Quramy** [comment]
;)
