### ISSUE TITLE
Cannot compile external modules unless the --module flag is provided

### ISSUE THREAD

**Issue by mvolkmann** [Quramy/tsuquyomi#28]
When I save a change to a file that exports things, I get the error message above.
I have a tsconfig.json in the top directory of my project and it specifies "module": "amd" in the "compilerOptions" section. Is there something else I need to do or does tsuquyomi not support this yet?

**Comment by Quramy** [comment]
Hi, @mvolkmann.

ummm, i can't reproduce this message.

If you don't mind, tell me your repo location where this message occurred.

Just for information, i create the following files(but this error didn't occur):

* tsconfig.json

```json
{
  "compilerOptions": {
    "module": "amd"
  }
}
```

* main.ts

```typescript
/// <reference path="subdir/sub.ts" />

module myModule {
    export class Awesome {
        private helper: Sub.Helper;
        constructor() {
            this.helper = new Sub.Helper();
        }
    }
}
```

* subdir/sub.ts

```typescript
module Sub {
    export class Helper { }
}
```

**Comment by mvolkmann** [comment]
Sorry, I had a typo in "compilerOptions" in my tsconfig.json file.

**Comment by Quramy** [comment]
@mvolkmann 

Your welcome :)

To omni-complete tsconfig.json(or package.json, bower.json, etc...) I've made another Vim plugin [Quramy/Vison](https://github.com/Quramy/vison).  If you're interested, please use it.

**Comment by sundayoyeniyi** [comment]
Hi 

I have this error with vscode 1.5 and below I can't find the problem with my tsconfig.json below:

````json
{
	"compilerOptions": {
		"target": "ES5",
		"module": "amd",
		"removeComments": true,
		"sourceMap": true
	}
}
````
Can you please tell me what I need to change?

SO

**Comment by Quramy** [comment]
Hi @sundayoyeniyi .

Are you using VisualStudio Code?

Here is a Vim plguin repository(not vscode!)
