### ISSUE TITLE
:TsuRenameSymbol doesn't work on Neovim

### ISSUE THREAD

**Issue by pablopunk** [Quramy/tsuquyomi#284]
I tried on `vim` and it does work. But, if I try it on nvim it just doesn't do anything, no errors and no questions (I mean the question that should ask for new name)

NVIM v0.3.4
Vi IMproved 8.0
MacOS 10.14.3
[.vimrc](https://github.com/pablopunk/dotfiles/blob/master/vim/vimrc)

**Comment by alexandcote** [comment]
Did you install `Shougo/vimproc.vim`?

**Comment by pablopunk** [comment]
Sorry, I use [coc.nvim](https://github.com/neoclide/coc.nvim/) now, so I won't try to reproduce this but I do remember installing `vimproc`. We can close this if no one else has the issue.
