### ISSUE TITLE
Show inferred type?

### ISSUE THREAD

**Issue by cmdcolin** [Quramy/tsuquyomi#297]
Sorry if this is naive but can this plugin show the inferred type of a function or variable?

 I am thinking sort of similar to this, doesn't have to be the same exact thing (inline), some tooltip or action to get the type would be fine too

https://marketplace.visualstudio.com/items?itemName=MartinJohns.inline-types

**Comment by felippenardi** [comment]
I'm looking for an answer on this too

**Comment by cmdcolin** [comment]
I ended up using the coc.nvim typescript config and it has a pointer for configuring your VIM in their README so that you press shift+k (e.g. capital K) while your cursor is on a variable and it pops out a hover window with the result https://github.com/neoclide/coc.nvim

**Comment by cmdcolin** [comment]
Specific line

```
" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>
```
