### ISSUE TITLE
Local tsserver checks for JS instead of script

### ISSUE THREAD

**Issue by bryanforbes** [Quramy/tsuquyomi#33]
Right now, `tsuquyomi#config#tsscmd()` checks for [`"node_modules/typescript/bin/tsserver.js"`](https://github.com/Quramy/tsuquyomi/blob/cc09dd7689ff2e721c65701b6ba61bebdff1ca3b/autoload/tsuquyomi/config.vim#L56). In newer releases (1.6+), all JavaScript files will be in `typescript/lib` and all scripts will be in `typescript/bin`. Because of this change, `tsuquyomi#config#tsscmd()` doesn't find a local `tsserver.js` for the nightlies. `tsuquyomi#config#tsscmd()` should instead be checking for `"node_modules/typescript/bin/tsserver"` since it exists in 1.5+ and can be passed to the node executable.

**Comment by Quramy** [comment]
@bryanforbes  
thanks your information.
