### ISSUE TITLE
File changes not being picked up

### ISSUE THREAD

**Issue by myitcv** [Quramy/tsuquyomi#34]
I have a TypeScript code generation process that re-runs when a definition file changes. However, `tsuquyomi` (or the underlying TSServer) doesn't seem to pick up this change, because the auto-complete suggestions presented don't include new methods/functions etc defined in the regenerated code.

Is this expected to work?

PS massive thanks for this project

**Comment by myitcv** [comment]
I've noticed that firing `:TsuquyomiReload` fixes things. Is there some way this can be made automatic?

**Comment by myitcv** [comment]
Actually, I'll take back that last comment; `:TsuquyomiReload` does not appear to fix things...

**Comment by Quramy** [comment]
Hi, @myitcv .

Right now, there is no function for automatic file change detection.

Please use `:TsuReloadProject` command after your generation process.
This command makes tsserver reload all buffers, so it may help your issue.

**Comment by myitcv** [comment]
Thanks
