### ISSUE TITLE
tsuquyomi#open() does not work well

### ISSUE THREAD

**Issue by Congee** [Quramy/tsuquyomi#39]
ENV:
I'm using Terminal.app + tmux on OSX
it works well under Terminal.app, but under tmux.

On OSX, /tmp is a soft link to /private/tmp

Given the file: `/tmp/hello.ts` :
When under tmux, `:echo tsuquyomi#bufManager#isOpened("/tmp/hello.ts")` outputs 1, however, `:echo tsuquyomi#bufManager#isOpened("/private/tmp/hello.ts")` outputs 0 and `expand("%:p")` echoes '/tmp/hellots'. I stepped into that fuction, only to found the variable `$file` is `/tmp/hello.ts`. Obviously, the problem has something to do with `link`.

I'm not familiar with this project, nor have enough time to handle it. I'd appreaciate it if you are to cope with it. 

PS: my gut feeling tell me that if can also be an upstream issue caused by tsserver's handling link.

**Comment by Congee** [comment]
I also found that this code bock:
``` viml
if g:tsuquyomi_auto_open
  call tsuquyomi#open()
endif
```
has been executed three times when loading a file into vim buffer. You can check `tsuquyomi#bufManager#isOpened(expand("%"))` to avoid unnecessary route.

**Comment by Quramy** [comment]
I didn't take out soft links or symbolic links.
`tsuquyomi#bufManager` uses only vim's buffer name, so `tsuquyomi#bufManager#isOpened('/private/tmp/hello.ts') does not return 1.

I use iTerm. I tried to create symbolic link and tried `TsuquyomiOpen` with a symbolic link file. It works well.

I don't understand why this error occurs under tmux and link...

**Comment by Congee** [comment]
Ok, it's irrelavent to tmux, it's a path problem, and I'm able to reproduce it.
Actually, I have a problem with `:echo tsuquyomi#hint()`
``` zsh
CC@/tmp $ echo "var a = 3;" > foo.ts
CC@/tmp $ vim /tmp/foo.ts
# `:echo tsuquyomi#hint()` under `a`, it prints `[Tsuquyomi] There is no hint at the cursor.`

CC@/tmp $ vim foo.ts
# `:echo tsuquyomi#hint()` under `a`, it prints `var a: number `
```
