### ISSUE TITLE
Support for showing the type of the identifier under the cursor

### ISSUE THREAD

**Issue by myitcv** [Quramy/tsuquyomi#40]
Would you consider adding support for a command that shows (via an `echom` perhaps?) the type of the identifier at the current cursor position?

e.g.

```typescript
// cursor position shown by '_'
let test_Var = "test";
```

call the new command, output at the bottom of the window is:

```
string
```

Thanks

**Comment by stefanpenner** [comment]
Oo, would be nice!

**Comment by derekpitt** [comment]
is `tsuquyomi#hint()` what you are looking for?

    autocmd FileType typescript nmap <buffer> <Leader>t : <C-u>echo tsuquyomi#hint()<CR>

**Comment by myitcv** [comment]
@derekpitt - amazing, yes, thanks very much for the pointer.

**Comment by stefanpenner** [comment]
Is there a way to get it to automatically  echo when for w/e is under the cursor ?

**Comment by myitcv** [comment]
@stefanpenner - you probably want to take a look at the [`CursorMoved`](http://vimdoc.sourceforge.net/htmldoc/autocmd.html#CursorMoved) `autocmd` event.

**Comment by stefanpenner** [comment]
@myitcv thanks for the tip, that looks on the mark.

**Comment by JKillian** [comment]
@stefanpenner Did you get it working well automatically? My vim knowledge is limited, so I wasn't sure how to set it up quite right.
