### ISSUE TITLE
file type bug with fugitive

### ISSUE THREAD

**Issue by co-dh** [Quramy/tsuquyomi#41]
I have a bug that the file type of a Gstatus will be set to typescript erroneously.
Here is my .vimrc
 "NeoBundle Scripts-----------------------------
if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

  " Required:
  set runtimepath+=/home/hao/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('/home/hao/.vim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

"  Essential
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'Shougo/vimproc.vim', {'build' : {'linux' : 'make'}}
NeoBundle 'Quramy/tsuquyomi'
NeoBundle 'bling/vim-airline'
call neobundle#end()

" Required:
filetype off
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
"End NeoBundle Scripts-------------------------

and here is the step to reproduce the bug:
1) open a .tsx file
2) :Gst
You'll find the .git/index buffer is detected as typescript.

This bug then becomes more serious because it will detect all other files as typescript.

**Comment by co-dh** [comment]
Ok, I figured it out myself as a programmer.
the autoload/tsuquyomi.vim:208 

if &previewwindow
    setlocal ft=typescript
endif

the setlocal here is too aggressive. Not every preview window is for typescript.
I commented it and the bug fixed.

**Comment by Quramy** [comment]
Hi @co-dh .

Thanks for your comments.

I wrote `setlocal ft=typescript` to high-lighting preview window in TypeScript's way.
And this code is not important. 

So, I'll delete this code to fix this issue.

**Comment by co-dh** [comment]
I forget to say thank you for make this plugin and I like it.
