### ISSUE TITLE
Avoid manual operation to install vimproc.vim with NeoBundle

### ISSUE THREAD

**Issue by fflorent** [Quramy/tsuquyomi#5]
I wonder why, instead of making manual post-install operation for vimproc.vim (to build it) in your [README](https://github.com/Quramy/tsuquyomi#how-to-install) file, you don't let NeoBundle do it for you, as explained here:
https://github.com/Shougo/vimproc.vim#neobundle

Florent

**Comment by Quramy** [comment]
Hi, Florent.

You're right, I write the configuration example of NeoBundle listed in the link in the README.

**Comment by fflorent** [comment]
Nice :).

Florent
