### ISSUE TITLE
Omni-complete on Object Properties

### ISSUE THREAD

**Issue by indiesquidge** [Quramy/tsuquyomi#50]
> _If you want to show a method's signature in the preview window when you complete this method's arguments:_

> _(The preview window isn't shown when completion properties or variables)_

Is there a way to make the completion for properties show up as soon as you type the `.` on an object? Something like the picture below, but without having to manually type `<C-x><C-o>` in insert mode in order to get it to show the window?

<img width="966" alt="screen shot 2015-12-18 at 8 54 04 pm" src="https://cloud.githubusercontent.com/assets/3409645/11911425/8a8ae9c8-a5c9-11e5-9859-f439eda91f7a.png">

**Comment by delphinus35** [comment]
I think you may use plugins such as [neocomplete.vim]. I can get it with the setting below, for example.

```vim
if !exists('g:neocomplete#force_omni_input_patterns')
  let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.typescript = '[^. \t]\.\%(\h\w*\)\?'
```

[neocomplete.vim]: https://github.com/Shougo/neocomplete.vim

**Comment by indiesquidge** [comment]
@delphinus35, thanks for the reply! I was using `neocomplete` for a file and absolutely loved it, the only problem is that I recently switched over to [neovim](https://github.com/neovim/neovim) completely as it's ability to have non-blocking, asynchronous plugins was a huge draw for me. Sadly, neovim [does not yet support](https://github.com/neovim/neovim/issues/1512) `neocomplete` since `neocomplete` has Lua scripting. I had switched over to `YouCompleteMe` but it's such a heavy plugin to load (benchmarking the startup time showed that this plugin alone took nearly 300 ms), and it was also interfering with `tsuquyomi`, so I had to remove that as well. However, the same guy that did `neocomplete` has a new completion plugin for neovim called [deoplete](https://github.com/Shougo/deoplete.nvim), but I can't get that to work correctly with omni-completion.

**Comment by indiesquidge** [comment]
**UPDATE**: I have since gotten `deoplete` to run omni-completion for properties and variables, and thankfully it plays nice with `tsuquyomi`. For anyone that comes across this in the future, you can [check out](https://github.com/indiesquidge/squidgefiles/blob/master/vim%2Fsettings%2Fcompletion.vim#L23) what I did to make it work. The feature [already existed by default](https://github.com/Shougo/deoplete.nvim/blob/17a3aee7b51858193fdfd5f02f7af763af44a465/autoload/deoplete/init.vim#L142) for some filetypes, but TypeScript was not one of them. I plan on creating a PR so that TypeScript will have this by default in `deoplete`, but I am [waiting](https://github.com/neovim/neovim/issues/1512#issuecomment-166243576) on the plugin's creator to see if he would be okay with that.
