### ISSUE TITLE
Scratch File Created on Completion

### ISSUE THREAD

**Issue by indiesquidge** [Quramy/tsuquyomi#51]
I'm not sure if this is a configuration setting for Vim that I just haven't learned about and therefore don't have set, but I've never seen it before and it only seems to happen in this plugin. When I run `<C-x><C-o>` to omni-complete a property, I always get this random `[Scratch]` file that pops up.
<img width="1440" alt="screen shot 2015-12-18 at 9 05 02 pm" src="https://cloud.githubusercontent.com/assets/3409645/11911460/099bee14-a5cb-11e5-85ab-f7338b34349c.png">
Is there a way to keep that new file from opening in my my current buffer? It's quite obtrusive.

Thanks a ton for making this plugin, it's incredible :)

**Comment by Quramy** [comment]
Hi @indiesquidge .

Do you want to hide the `[Scratch]` window?

So, write the following to your .vimrc:

```vim
  autocmd FileType typescript setlocal completeopt-=preview
```

**Comment by indiesquidge** [comment]
@Quramy, perfect! I didn't realize that was what the preview window was :blush: Thanks for the help!
