### ISSUE TITLE
Tsuquyomi doesn't pick up new file settings correctly

### ISSUE THREAD

**Issue by reissbaker** [Quramy/tsuquyomi#53]
When adding a new file to an existing project with an existing `tsconfig.json` and attempting to write to the new file, Tsuquyomi prints the following error message: `error| Cannot compile modules unless the '--module' flag is provided.`. However, the module flag *is* provided in the project's `tsconfig.json`, and restarting Vim fixes the problem — Tsuquyomi stops printing bogus error messages on write.

I've tried a few things to fix the problem, like running `:TsuReloadProject`, but nothing seems to fix it other than a full Vim restart. Any ideas?

**Comment by Quramy** [comment]
Hi, @reissbaker .

I don't know why `:TsuReloadProject` doesn't work...

I want to reproduce your issue. So please tell me the more detailed procedure(your `tsconfig.json`, directory structure of your project).

**Comment by reissbaker** [comment]
Sure thing. Here's my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": true,
    "target": "es5",
    "jsx": "react",
    "outDir": "build/"
  },
  "files": [
    "index.tsx"
  ]
}
```

My directory structure is pretty standard: a `lib/` folder that code goes in, with some subdirectories inside that. As far as I can tell it doesn't matter where in `lib/` I put the new files; the `tsconfig.json` still doesn't get picked up for new files until I restart Vim. Here's a sample file I put in `lib/test.ts` that exhibits the problem:

```typescript
'use strict';

import * as _ from 'underscore';

export const test = {};
```

**Comment by Quramy** [comment]
Thanks, I'm going to try to reproduce.

**Comment by reissbaker** [comment]
Oh, it looks like running:

```
:TsuStopServer
:TsuStartServer
```

Will get Tsu to stop complaining without a Vim restart, although it still seems worth the bug report that you have to manually restart the server when new files are added.

**Comment by Quramy** [comment]
I reproduced your error and fixed it with the following `tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": true,
    "target": "es5",
    "jsx": "react",
    "outDir": "build/"
  },
  "exclude": ["node_modules"]
}
```

Please try it.

**Comment by reissbaker** [comment]
Nice, it works.

**Comment by reissbaker** [comment]
(And thank you!)
