### ISSUE TITLE
Support for tsconfig filesGlob

### ISSUE THREAD

**Issue by chrisnicola** [Quramy/tsuquyomi#54]
The `filesGlob` options for tsconfig.json is supported by the tsconfig utility in NPM, however tsuquyomi ignores it and so you get errors from any files you are expecting it to pick up.

Is it a simple thing to support this?

**Comment by Quramy** [comment]
Hi @chrisnicola .

It's difficult to support 'filesGlob' .

The schema of tsconfig defined by MicroSoft([see original file](http://json.schemastore.org/tsconfig)) has no key 'filesGlob'.

And tsuquyomi does not have parser of tsconfig.json.
tsuquyomi delegates parsing it(and any .ts files) to tsserver, which is bundled into typescript natively.

**Comment by chrisnicola** [comment]
The `tsconfig` tool adds support for `filesGlob` and Typescript will supposedly support it in 2.0. For some reason Webpack works with `tsconfig` when it is installed via NPM.

https://github.com/TypeStrong/tsconfig

May not be trivial to support this, but it would be handy. For now I've had to disable tsuquyomi on my projects, but hopefully when 2.0 comes out things will stabilize a bit.

**Comment by fluffywaffles** [comment]
TypeScript has actually opted to support "include" instead of "filesGlob." The API is functionally the same, I believe, except that it's not part of the compilerOptions map, it's specified separately in tsconfig.

**Comment by Quramy** [comment]
As @skorlir said, you can use the "include" option instead of "filesGlob".
