### ISSUE TITLE
False warning of experimentalDecorators 

### ISSUE THREAD

**Issue by mhartington** [Quramy/tsuquyomi#56]
Hey there. So it seems that in my current projects tsconfig is being ignored for a project

<img width="1680" alt="screen shot 2016-01-23 at 8 14 59 am" src="https://cloud.githubusercontent.com/assets/2835826/12531274/f93e417e-c1aa-11e5-8024-93f879999f75.png">
<img width="1680" alt="screen shot 2016-01-23 at 8 15 10 am" src="https://cloud.githubusercontent.com/assets/2835826/12531275/f9419a68-c1aa-11e5-88e2-8a473189a623.png">

Any time I use an experimental decorator, I get a warning, even though I have the compiler option for decorators enabled. Any ideas?

**Comment by delphinus35** [comment]
It seems tsuquyomi does not read `tsconfig.json`. It might be fixed if you place `tsconfig.json` at upper paths `/`, `/app/`, `/app/pages/`, or `/app/pages/page1/`.

**Comment by mhartington** [comment]
After some more digging, it seems to be due to neomake, not tsuquyomi. Sorry for the noise! 

Cheers

**Comment by metal3d** [comment]
@mhartington I've got the same problem. I don't use neomake, I'm using "ng" command to generate my angular2 project and I've got the same warning.

Any idea ?

My tsconfig is:

```json
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "mapRoot": "",
    "module": "system",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitAny": false,
    "outDir": "../dist/",
    "rootDir": ".",
    "sourceMap": true,
    "sourceRoot": "/",
    "target": "es5"
  }
}
```

Vim is opened where the tsconfig file resides...

**Comment by mhartington** [comment]
Hmm, not seeing this in my test. Are you using syntastic?

**Comment by metal3d** [comment]
I found a workaround, see https://github.com/leafgarland/typescript-vim/issues/47 
The problem was that syntastic didn't checked typscript.json file

**Comment by chapati23** [comment]
this workaround does _not_ work for me (using neovim 0.1.4)

no matter where i put my tsconfig.json — tsuquyomi does not seem to pick it up :(

**Comment by chapati23** [comment]
@mhartington: could you elaborate on your digging? just wanna make sure i don't have the same problem

**Comment by vyorkin** [comment]
@chapati23 Have you figured it out? @metal3d I have the same problem, setting `let g:syntastic_typescript_tsc_fname = ''` doesn't help

**Comment by chapati23** [comment]
@vyorkin working for me now. unfortunately i couldn't tell you what change helped at the end because i just reinstalled and refactored my whole neovim installation :-/
