### ISSUE TITLE
Cannot find interfaces if definition file is in the same path as ts file

### ISSUE THREAD

**Issue by indiesquidge** [Quramy/tsuquyomi#58]
Let's say I have a project with the following set up:

```sh
app
└── directives
    └── popover
        ├── popover.d.ts
        └── popover.ts
```

Where `popover.ts` has some property that uses an interface name (lets call it `IPopoverConfig`) defined in `popover.d.ts`.

When I open `popover.ts` and save, I get an error saying something along the lines of

```sh
app/directives/popover/popover.ts|6 col 37 error| Cannot find name 'IPopoverConfig'.
```

The error is not "real", meaning that with my compile and build tasks, I can get the whole TypeScript app to work without problems. So it seems a bit strange. Especially considering that I have another folder, `typings`, that is a sibling to `app`, which contains other definition files that I am using that I'm not getting errors on. 

```sh
app/
typings
├── some-file.d.ts
└── some-other-file.d.ts
```

If I include a reference path to `popover.d.ts` in `popover.ts`
```ts
/// <reference path="./popover.d.ts" />
```
Everything works fine.

If I move `popover.d.ts` into my `typings` directory, everything works fine.
In fact, if I move `popover.d.ts` into _any_ directory that isn't `app/directives/popover`, everything works fine.
It seems the only time I get an error complaining about not finding the interfaces defined in `popover.d.ts` is when it is in the same path as `popover.ts`.

I'm not sure why this is. I am not sure how `tsuquyomi` traverses a project directory structure at compile time, but have you ever seen a case where definition files somehow appear "invisible" to the corresponding TypeScript files in the same path unless you include a reference path? Any light you can shed on this would be appreciated greatly.

FWIW, my co-worker using `atom-typescript` does not seem to have this issue. I would prefer to continue using `vim` and I love this TypeScript plugin and am thankful for all the work you've done on it, it's just this one thing that's causing a problem. If it's unsolvable for the time being, I can just make sure to have all of my definition files not in the same path as any `.ts` files using them.

Thanks.

**Comment by Quramy** [comment]
I think it's in the specification of TypeScript.
TypeScript uses `popover.ts` in the preference to `popover.d.ts` in the following code:

```ts
/* main.ts */
import * as Popover from './popover';
```

In this case the `popover.d.ts` is not referenced in your project, so you should write `/// <reference path="./popover.d.ts" />` explicitly.

I don't know implementation of `atom-typescript`. But my vim plugin does not have any code of module-resolution.
My plugin delegates procedure of module-resolution to `tssserver`(in other words, TypeScript language service).

**Comment by indiesquidge** [comment]
@Quramy I believe the reason `tsconfig.json` was invented was to negate the necessity for reference paths or `import` statements, and is part of . It gives you compilation options and files (or exclusions) that work across a project. `tsuquyomi` works in most cases, but it breaks whenever I put a definition file in the same path as a file who is implementing some of those definitions. This is fine; I can move my definition files to their own folder. I just wanted to make you aware of what I came across.

Awesome plugin, by the way. It's saved me from so many headaches when dealing with large TypeScript projects. Keep up the good work :)
