### ISSUE TITLE
Showing type information instead of `import` in `tsuquyomi#hint`

### ISSUE THREAD

**Issue by ianks** [Quramy/tsuquyomi#59]
Given a file `a.ts`:

```typescript
// a.ts
export default class A {
  name: string;
  age: number;
}
```

And a file `b.ts`;

```typescript
import A from './a.ts';

A // put vim cursor over A, and run :echo tsuquyomi#hint()
  // output: `import A`
```

In this case, you can see that the only information given back is that it is `import A`.  Is there a way to get back the type information of A as opposed to just the `import A`?

**Comment by Quramy** [comment]
Sorry for my late reply. Sadly, tsuquyomi(and typescript language service) can't fetch transitive hint information.
