### ISSUE TITLE
modify reload command to suit typescript 1.9.x

### ISSUE THREAD

**Issue by Quramy** [Quramy/tsuquyomi#62]
Tsuquyomi should ignore the 2nd response of `reload` command.

See https://github.com/Microsoft/TypeScript/issues/8434.

**Comment by Quramy** [comment]
@myitcv I think I can fix your issue with typescript1.9.x. Please check out .

**Comment by myitcv** [comment]
@Quramy will try it right away - thanks for the quick response!

**Comment by myitcv** [comment]
Seems to be working well so far! I'll write back here in case I see any issues.
