### ISSUE TITLE
Cannot find module 'anymodulehere'

### ISSUE THREAD

**Issue by vyorkin** [Quramy/tsuquyomi#67]
repo to reproduce: https://github.com/vyorkin/disengaged

steps to reproduce:

0. `npm i` – it will install modules as well as typings
1. open `examples/base/index.tsx`
2. `:w`

details:

I'm using neovim, here is the `:version` output: https://gist.github.com/vyorkin/87edba81b81984dfc515645f1ce3e552

Here is my syntastic config: https://github.com/vyorkin-personal/dots/blob/master/tag-vim/vim/plugin/syntastic.vim

**Comment by vyorkin** [comment]
ok, I think I've got it, its because of `pretty` option

**Comment by Quramy** [comment]
I @vyorkin, tsuquyomi provides checker for syntastic .  Please try the following :

```vim
let g:tsuquyomi_disable_quickfix = 1
let g:syntastic_typescript_checkers = ['tsuquyomi'] " You shouldn't use 'tsc' checker.
```

**Comment by vyorkin** [comment]
yeah, sorry, I didn't commit my changes to dotfiles, its already there, I mean this 2 lines:
```
let g:tsuquyomi_disable_quickfix = 1
let g:syntastic_typescript_checkers = ['tsuquyomi']
```

**Comment by Quramy** [comment]
ummm.... I've attempted to reproduce it using your repo(in examples/basic dir), but I can't .

my env:

* os: OS X 10.10.3
* term: iTerm2 2.1.4
* vim: 
 * classical vim: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 18 2016 02:46:29)
 * nvim: NVIM v0.1.5-172-gd02cfe8
* Node.js: v6.1.0
* typescript: v1.8.10

**Comment by vyorkin** [comment]
ok, thank you again @Quramy, I'll close this for now, I need to double check my env

**Comment by vyorkin** [comment]
@Quramy I've updated my neovim to `NVIM v0.1.5-357-g8bf94f8 Build type: Dev` and now I've got different errors:
```
examples/basic/src/components/Hello.tsx|14 col 10 error| JSX element attributes type 'IMessageProps & { children?: ReactElement<any> | string | number | {} | (ReactElement<any> | stri...' must be an object type.
examples/basic/src/components/Hello.tsx|15 col 10 error| JSX element attributes type 'P & { children?: ReactElement<any> | string | number | {} | (ReactElement<any> | string | number ...' must be an object type.
```

**Comment by Quramy** [comment]
@vyorkin . I don't know why you got the errors... Do you have any compile errors if you execute `tsc` in your terminal?

**Comment by vyorkin** [comment]
No, I've tried almost everything, still have no idea whats wrong. I'll try to reproduce on virtual machine

**Comment by vyorkin** [comment]
got it working, after adding `reference` here https://github.com/vyorkin-play/hello/blob/master/src/index.tsx#L1
