### ISSUE TITLE
Vim becomes unresponsive when I save a file.

### ISSUE THREAD

**Issue by eggers** [Quramy/tsuquyomi#71]
Anytime I save a ts file, my vim freezes. It only started happening after I recently upgraded my vim plugins & nvim instance. However, the following work just fine:

`:TsuDefinition`
`:TsuGeterr`
`:TsuGeterrProject`

Also, if I remove `airblade/vim-gitgutter`, it works just fine as well.

**Comment by indiesquidge** [comment]
@eggers, you might want to read through this [open issue thread](https://github.com/Quramy/tsuquyomi/issues/55) for some context around this. [This issue](https://github.com/Quramy/tsuquyomi/issues/57) could be helpful as well.

**Comment by eggers** [comment]
@indiesquidge Thanks. I hadn't seen that issue for some reason. I also traced it down to git-gutter and switched to signify which fixed my issue.

Closing as dup of #55

**Comment by vitaly-zdanevich** [comment]
I have the same problem :(
