### ISSUE TITLE
Creating import statements with single quotes.

### ISSUE THREAD

**Issue by aaronlahey** [Quramy/tsuquyomi#75]
ES6 import statements seem to be generated as...

```typescript
import { Foo } from "./foo"
```

Is it possible to change the quotes from double to single?

Thanks!

**Comment by Quramy** [comment]
Hi, @aaronlahey . Thanks for your feedback :)

Ok, I'll make an option that allows this.

**Comment by aaronlahey** [comment]
Excellent! Thanks for the quick response.

**Comment by Quramy** [comment]
@aaronlahey 

I added the new option `g:tsuquyomi_singlequate_import` . Please check it out

```vim
" your .vimrc
let g:tsuquyomi_singlequate_import = 1
```

**Comment by aaronlahey** [comment]
It seems to work great. You have a typo in the option, though. It should read `tsuquyomi_singlequote_import` instead of `tsuquyomi_singlequate_import`.

**Comment by aaronlahey** [comment]
It would also read more clearly if it were `tsuquyomi_single_quote_import`. Thanks for implementing this so quickly.

**Comment by Quramy** [comment]
Oooops ! I'll rename it to `tsuquyomi_single_quote_import`. please wait...

**Comment by aaronlahey** [comment]
Awesome. I can confirm this works with the rename.
