### ISSUE TITLE
Balloons only appear after manually sourcing .vimrc

### ISSUE THREAD

**Issue by iscekic** [Quramy/tsuquyomi#83]
My .vimrc : https://github.com/Torwori/dotfiles/blob/master/.vimrc#L110

The balloons do not appear when first opening a typescript file, `:echo tsuquyomi#balloonexpr()` returns `0`. After manually sourcing with `:source ~/.vimrc`, everything works as expected.

Interistingly, `:echo tsuquyomi#hint()` always works ok.

**Comment by Quramy** [comment]
The `tsuquyomi#balloonexpr()` function returns `0` if tsserver has no information about the identifier under the cursor(Sorry, it isn't good that it displays `0` on the balloon, see https://github.com/Quramy/tsuquyomi/issues/73#issuecomment-228034386 )

**Comment by Torwori** [comment]
But it has info after sourcing.

1) Open .ts file
2) `:echo tsuquyomi#balloonexpr()` when cursor is on class property -> result is `0`
3) `:echo tsuquyomi#hint()` gives correct info `(property) Test.property: number`
4) `:source ~/.vimrc`
5) `:echo tsuquyomi#balloonexpr()` gives correct info now, balloon appears too

**Comment by Torwori** [comment]
It seems to be a conflict with [syntastic](https://github.com/scrooloose/syntastic), once I disable it everything works properly.

I tried setting `let g:syntastic_enable_balloons = 0` but it isn't working.

**Comment by Quramy** [comment]
What's order of `let g:syntastic_enable_balloons = 0` and `autocmd BufNewFile,BufRead Typescript setlocal balloonexpr=tsuquyomi#balloonexpr()` ?

Does following configure fix your issue?

```vim
let g:syntastic_enable_balloons = 0

" other settings..

`autocmd BufNewFile,BufRead Typescript setlocal balloonexpr=tsuquyomi#balloonexpr()
```

**Comment by Torwori** [comment]
No, the issue remains regardless of order.

**Comment by Quramy** [comment]
Syntastic sets `balloonexpr` at https://github.com/scrooloose/syntastic/blob/master/plugin/syntastic/balloons.vim#L29 .

And it seems `let g:syntastic_enable_balloons = 0` does not allow to override the `balloonexpr` var.

**Comment by Torwori** [comment]
So is a solution possible?

**Comment by Quramy** [comment]
Ummm, sorry, I don't have good idea...
