### ISSUE TITLE
Sort completion entries the same way as Visual Studio Code

### ISSUE THREAD

**Issue by dannysu** [Quramy/tsuquyomi#88]
Documenting the issue for PR #87.

tsserver has support for JavaScript through its [JavaScript "Salsa" language service](https://github.com/Microsoft/TypeScript/wiki/Salsa).

Using the following sample .js file:
```
'use strict';

class Child {
    constructor(row, column) {
        this.property1 = row;
        this.property2 = column;
    }

    static method1() {
    }

    method2() {
    }
}
```

Visual Studio Code shows the following completion entries after `this.`:
![screenshot from 2016-10-15 10-01-19](https://cloud.githubusercontent.com/assets/859317/19411883/a7b79e46-92be-11e6-84e9-46b7c7d140e1.png)

Tsuquyomi shows the following:
![screenshot from 2016-10-15 10-04-36](https://cloud.githubusercontent.com/assets/859317/19411893/d87f71d4-92be-11e6-86b2-decf6d7b647c.png)

Note that the entries are out-of-order compared to Visual Studio Code. The more important entries are mixed together with other strings due to the alphabetical sorting.

A similar file implemented in TypeScript has no such problems:
![screenshot from 2016-10-15 10-07-28](https://cloud.githubusercontent.com/assets/859317/19411918/6e15b1f4-92bf-11e6-83ed-516193e0ced4.png)

So this sorting issue only impacts tsserver when used with JavaScript files.

**Comment by Quramy** [comment]
@dannysu Thanks for your explain, and PRs :)
