### ISSUE TITLE
tsserver is not install error.

### ISSUE THREAD

**Issue by rajinder-yadav** [Quramy/tsuquyomi#94]
Hi I am using gvim on Linux and I am getting an error stating, "tsserver is not install error". As a result this plugin doesn't work for me.

```bash
$ npm list -g --depth=0
/opt/local/lib
├── angular-cli@1.0.0-beta.19-3
├── js-beautify@1.6.4
├── jshint@2.9.4
├── jslint@0.10.3
├── npm@4.0.2
├── tslint@3.15.1
├── typescript@2.0.7
└── typescript-formatter@4.0.0
```

**Comment by Quramy** [comment]
In your gvim, is PATH configured?

Exec the following in your gvim:

```vim
echo executable('tsserver')
```

If it returns 0, gvim does not recognize the installed tsserver.

**Comment by rajinder-yadav** [comment]
OK you answer help me figure it out, I started gvim using a short cut and not from the terminal. As a result exec `:echo $PATH` was different than my PATH from the terminal.

A fix to getting it to work with gvim launched from a taskbar menu or shortcut was to add the following to my **.vimrc**

`let $PATH=$PATH . ':/path/to/tsserver'

You might want to add this to your README if it's not already there.
