### ISSUE TITLE
Support code fixes api

### ISSUE THREAD

**Issue by mkusher** [Quramy/tsuquyomi#97]
tsserver now has this nice feature:

https://github.com/Microsoft/TypeScript/pull/10185
https://github.com/Microsoft/TypeScript/issues/6943

it would be nice to add support in tsuquyomi

**Comment by Quramy** [comment]
Yeah. I'm working this on `ts2.1` branch and #98 :)

**Comment by mkusher** [comment]
@Quramy 👍 , so this is duplicate then
